attach(AdvertisingDS)
step(lm(Sales~1), direction = "forward", scope = ~TV+Radio+Newspaper)
step(lm(Sales~TV+Radio+Newspaper), direction = "backward")
step(lm(Sales~TV+Radio+Newspaper), direction = "both")
model <- lm(Sales~TV+Radio)
anova(model)
summary(model)
model1 <- lm(Sales~TV*Radio)
anova(model1)
summary(model1)
